apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-runs
rules:
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - runs
      - experiments
      - jobs
    verbs:
      - get
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list