apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-runs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-runs
subjects:
  - kind: User
    name: REPLACE-USER