apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: modelmesh-metrics-monitor
  labels:
    modelmesh-service: modelmesh-serving
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 30s
      port: prometheus
      scheme: https
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      modelmesh-service: modelmesh-serving
