apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-pipeline
spec:
  template:
    spec:
      volumes:
        - name: proxy-tls
          secret:
            secretName: ds-pipelines-proxy-tls
      containers:
        - name: oauth-proxy
          args:
            - --https-address=:8443
            - --provider=openshift
            - --openshift-service-account=ds-pipeline
            - --upstream=http://localhost:8888
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
            - '--openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
            - --skip-auth-regex='(^/metrics|^/apis/v1beta1/healthz)'
            - --pass-user-headers="true" # Header: X-Forwarded-User
          image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.8
          ports:
            - containerPort: 8443
              name: https-oauth
          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-tls
      serviceAccountName: ds-pipeline
