podsPerRuntime: 2
headlessService: true
modelMeshImage:
  name: quay.io/tteofili/modelmesh
  tag: latest
modelMeshResources:
  requests:
    cpu: "300m"
    memory: "448Mi"
  limits:
    cpu: "3"
    memory: "448Mi"
restProxy:
  enabled: true
  port: 8008
  image:
    name: quay.io/opendatahub/rest-proxy
    tag: v0.1.4
  resources:
    requests:
      cpu: "50m"
      memory: "96Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
storageHelperImage:
  name: quay.io/opendatahub/modelmesh-runtime-adapter
  tag: v0.9.0
  command: ["/opt/app/puller"]
storageHelperResources:
  requests:
    cpu: "50m"
    memory: "96Mi"
  limits:
    cpu: "2"
    memory: "512Mi"
serviceAccountName: ""
metrics:
  enabled: true