apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base
- ../../default
configMapGenerator:
- files:
  - config-defaults.yaml
  name: model-serving-config-defaults
  behavior: merge

