apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base
configMapGenerator:
- files:
  - config-defaults.yaml
  name: model-serving-config-trustyai
#patchesStrategicMerge:
#  - manager.yaml

