apiVersion: v1
kind: Secret
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: mysql-secret
stringData:
  password: root_password   # override this
  username: root   # override this
