kind: Deployment
apiVersion: apps/v1
metadata:
  name: rhods-prometheus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rhods-prometheus-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: rhods-prometheus-operator
        app.kubernetes.io/version: 4.11.0-0.57
        k8s-app: rhods-prometheus-operator
      annotations:
        repository: 'https://github.com/prometheus-operator/prometheus-operator'
        capabilities: Deep Insights
        description: >-
          Manage the full lifecycle of configuring and managing Prometheus and
          Alertmanager servers.
    spec:
      serviceAccountName: rhods-prometheus-operator
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          name: prometheus-operator
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.namespace'
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: registry.redhat.io/openshift4/ose-prometheus-operator:v4.11.0-202211072116.p0.gcb3afa2.assembly.stream
          args:
            - '-alertmanager-config-namespaces=$(NAMESPACE)'
            - '-alertmanager-instance-namespaces=$(NAMESPACE)'
            - '-prometheus-instance-namespaces=$(NAMESPACE)'
            - '-thanos-ruler-instance-namespaces=$(NAMESPACE)'
            - --prometheus-config-reloader=registry.redhat.io/openshift4/ose-prometheus-config-reloader:v4.11.0-202211072116.p0.gcb3afa2.assembly.stream
            - --prometheus-default-base-image=registry.redhat.io/openshift4/ose-prometheus:v4.11.0-202211072116.p0.ge751c61.assembly.stream
            - --alertmanager-default-base-image=registry.redhat.io/openshift4/ose-prometheus-alertmanager:v4.11.0-202211072116.p0.g05cfc39.assembly.stream
  revisionHistoryLimit: 1
