apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odh-prometheus-operator
roleRef:
  kind: ClusterRole
  name: odh-prometheus-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: $(deployment-namespace)
    name: odh-prometheus-operator
