apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: rhods-model-monitoring
  name: rhods-model-monitoring
spec:
  serviceAccountName: rhods-model-monitoring-sa
  listenLocal: true
  containers:
    - args:
        - '-https-address=:8443'
        - '-provider=openshift'
        - '-openshift-service-account=rhods-model-monitoring-sa'
        - '-upstream=http://localhost:9090'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
        - '--openshift-sar={"namespace": "redhat-ods-monitoring", "resource": "services", "verb": "get"}'
        - '--openshift-delegate-urls={"/": {"namespace": "redhat-ods-monitoring", "resource": "services", "verb": "get"}}'
        - '-skip-auth-regex=^/metrics'
      image: 'registry.redhat.io/openshift4/ose-oauth-proxy:v4.8'
      imagePullPolicy: Always
      name: oauth-proxy
      ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/tls/private
          name: prometheus-tls
        - mountPath: /etc/oauth/config
          name: oauth-config
  serviceMonitorSelector:
    matchLabels:
      modelmesh-service: modelmesh-serving
  volumes:
    - name: prometheus-tls
      secret:
        secretName: serving-prometheus-proxy-tls
    - name: oauth-config
      secret:
        secretName: rhods-monitoring-oauth-config-generated
  replicas: 3
