kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.prometheus: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"rhods-model-monitoring"}}'
  name: rhods-model-monitoring-sa
  namespace: redhat-ods-monitoring
